
export const PRESETS = {
  profile: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile3.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile4.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile5.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile6.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Profile7.png",
  ],
  upperBody: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper3.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper4.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper5.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper6.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Upper7.png",
  ],
  lowerBody: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower3.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower4.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower5.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Lower6.png",
  ],
  footwear: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes3.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes4.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes5.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Shoes6.png",
  ],
  headwear: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Headware1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Headware2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Headware3.png",
  ],
  accessories: [
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag1.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag2.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag3.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag4.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag5.png",
    "https://raw.githubusercontent.com/AAAlexanderS/AI-TRYON/main/Library/Bag6.png",
  ],
};
